# Generated by Django 5.2.1 on 2026-01-06 17:24

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.CharField(default=website.models.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
